[package]
name = "chomp-bench"
version = "0.1.0"
authors = ["Greg Brown <gmb60@cam.ac.uk>"]
edition = "2018"

[dependencies]
chewed = {path = "../chewed"}
chomp-macro = {path = "../chomp-macro"}

[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "json"
harness = false
