//! A typed, algebraic parser generator.
#![warn(absolute_paths_not_starting_with_crate)]
#![warn(anonymous_parameters)]
#![warn(deprecated_in_future)]
#![warn(elided_lifetimes_in_paths)]
#![warn(keyword_idents)]
#![warn(macro_use_extern_crate)]
#![warn(meta_variable_misuse)]
#![warn(missing_copy_implementations)]
#![warn(missing_debug_implementations)]
#![warn(non_ascii_idents)]
#![warn(private_doc_tests)]
#![warn(single_use_lifetimes)]
#![warn(trivial_numeric_casts)]
#![warn(unaligned_references)]
#![warn(unreachable_pub)]
#![warn(unused_crate_dependencies)]
#![warn(unused_import_braces)]
#![warn(unused_lifetimes)]
#![warn(unused_qualifications)]
#![warn(variant_size_differences)]

#![warn(clippy::pedantic)]
#![allow(clippy::filter_map)]
#![allow(clippy::find_map)]
#![allow(clippy::missing_errors_doc)]
#![allow(clippy::module_name_repetitions)]
#![allow(clippy::must_use_candidate)]

#![warn(clippy::dbg_macro)]
#![deny(clippy::exit)]
#![warn(clippy::expect_used)]
#![deny(clippy::float_arithmetic)]
#![warn(clippy::get_unwrap)]
// #![warn(clippy::indexing_slicing)]
#![deny(clippy::integer_division)]
#![warn(clippy::let_underscore_must_use)]
#![warn(clippy::let_unit_value)]
#![warn(clippy::map_err_ignore)]
#![warn(clippy::mem_forget)]
#![deny(clippy::modulo_arithmetic)]
#![warn(clippy::multiple_inherent_impl)]
#![deny(clippy::panic)]
#![warn(clippy::panic_in_result_fn)]
#![deny(clippy::print_stderr)]
#![deny(clippy::print_stdout)]
#![warn(clippy::rest_pat_in_fully_bound_structs)]
#![warn(clippy::str_to_string)]
#![warn(clippy::string_add)]
#![warn(clippy::string_to_string)]
#![deny(clippy::todo)]
#![warn(clippy::unimplemented)]
#![warn(clippy::unneeded_field_pattern)]
#![warn(clippy::unwrap_in_result)]
#![warn(clippy::unwrap_used)]
#![warn(clippy::wildcard_enum_match_arm)]

pub mod chomp;
pub mod lower;
pub mod nibble;
